# Generated by Django 5.1.1 on 2024-09-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraire',
            name='end_lat',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='end_lng',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='start_lat',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='start_lng',
        ),
        migrations.AddField(
            model_name='itineraire',
            name='coordinates',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
